### ISSUE TITLE
Images don't work correctly between color formats?

### ISSUE THREAD

**Issue by DianaNites** [jamwaffles/embedded-graphics#423] opened 2020-08-09 18:49 UTC
- Version of embedded-graphics in use (if applicable): 0.6.2
- Target: QEMU 5.0.0
- If using real hardware: Custom

## Description of the problem/feature request/other

Okay, so first some background:

I'm using this crate for graphics in QEMU OVMF UEFI, which only knows the pixel format at runtime,
so I've implemented `DrawTarget` generically over `Into<Bgr888>` and just use `Rgb888::from` if need be.(blt and pixel bitmask currently unsupported). So far so good, the circle and some text example colors are correct, despite the code using `Rgb565`.

And onto the issue:

Then I wanted to display images, and found that `Image<Tga, Rgb888>` results in the colors being wrong. It compiles, it should be converting through `Into<Bgr888>`, yet the colors are wrong?

**Comment by rfuest** [comment] 2020-08-09 19:04
I think this should work like you described it.

Just to make sure the problem is in the color conversion and not in the TGA decoding: Does https://github.com/jamwaffles/embedded-graphics/blob/master/simulator/examples/assets/rust-pride.tga show the same color problems?

**Comment by DianaNites** [comment] 2020-08-09 19:16
Okay so i've tried both tga and bmp, of rust-pride and my own test image

Rust-pride.tga is incorrect, red and blue reversed.
![Screenshot_20200809_150758](https://user-images.githubusercontent.com/5275194/89739868-2a4bb700-da52-11ea-94e2-6b5cf9bfb368.png)

rust-pride.bmp Bgr888 is even weirder, with
![Screenshot_20200809_151226](https://user-images.githubusercontent.com/5275194/89739925-be1d8300-da52-11ea-9fcf-d543ed5cdb0c.png)
and this for Rgb888 
![Screenshot_20200809_151250](https://user-images.githubusercontent.com/5275194/89739930-ce356280-da52-11ea-852c-ce5ec9c93907.png)

The same bmp color issue does not occur with my own test bmp image with Bgr888 though, oddly enough? Does bmp support different color formats and does mine just so happen to already be bgr, and the rust-pride one isnt, or something?

![Screenshot_20200809_151421](https://user-images.githubusercontent.com/5275194/89739955-063ca580-da53-11ea-9463-019a3d21832d.png)

**Comment by rfuest** [comment] 2020-08-09 19:25
`rust-pride.bmp` is a 16 BPP `Rgb565` image, which should explain the weird colors for the BMP file.

Did you implement `draw_image` in your `DrawTarget` impl or are you using the default implementation?

Could you try to manually convert the colors? `image.into_iter().map(|Pixel(p, c)| Pixel(p, Rgb888::from(c))).draw(&mut display)`

**Comment by DianaNites** [comment] 2020-08-09 19:27
My `DrawTarget` uses the default.

I'll try manually converting the colors

**Comment by DianaNites** [comment] 2020-08-09 19:29
Manually converting the colors with `image.into_iter().map(|Pixel(p, c)| Pixel(p, Bgr888::from(c))).draw(&mut display)` did not work?

**Comment by DianaNites** [comment] 2020-08-09 19:32
re: rust-pride.bmp, using `Image<Bmp, Rgb565>` does indeed fix the rendering issue, the colors are still wrong though.

**Comment by rfuest** [comment] 2020-08-09 19:55
Did I understand you initial post correctly that you `DrawTarget` currently stores `Bgr888` colors into the framebuffer by converting them by something like: `color.into_storage()`? And that the `Rgb888::from`, you mentioned, is only used if UEFI reports another pixel format?

There were some issues with implementing `DrawTarget` for generic color types in the past. To debug the problem I would suggest to try tp implement `DrawTarget` for `Bgr888` (or whatever type the framebuffer uses) instead of a generic version.

**Comment by DianaNites** [comment] 2020-08-09 20:05
Yes you understand correctly, thats what I'm doing. It's generic over `Into<Bgr888>`, which covers all the other color types.

Also, a question, the `C` in `Image`, hows it used? Because the rust-pride bmp rendered and colored wrong without Rgb565 for `C`, so is `C` used for interpreting the images pixels *and* for writing them out? Wouldn't that mean it's impossible to use images that you don't know the exact format of in advance?

**Comment by rfuest** [comment] 2020-08-09 20:19
> Also, a question, the `C` in `Image`, hows it used? I ask because `rust-pride.bmp` rendered and colored wrong without `Rgb565` for `C`, so does that mean `C` is used for interpreting the images pixels _and_ for writing them out?

Yes, that's correct. That's why I suggested to manually convert the color type during drawing, because `DrawTarget::draw_image` was a last image addition to embedded-graphics `0.6` and never supported color conversion. And by implementing `DrawTarget` generically over `C` this can lead to wrong inferred typed by the compiler.

> Wouldn't that mean it's impossible to use images that you don't know the exact format of in advance?

Yes, that's also correct. I also noticed this while I did some work on the image support recently while working on some features for the next version of embedded-graphics. This isn't a huge problem for most embedded applications which can bundle the correctly formatted images, but it would be a nice to have feature none the less.

**Comment by DianaNites** [comment] 2020-08-09 21:26
In that case I think the color conversions are actually working fine, so long as the `C` for `Image` is correct

I think the problems are then:

1. The docs aren't clear that the `C` for `Image` is for the image data, not the display.(Which I now notice `draw_image` is generic)

2. It's impossible to use images you don't statically know the format of in advance. You can't just load and display an image.

The second one in particular is annoying, I'd like to display user-supplied images without a lot of hassle on their part. For now I guess a workaround is require them to use a specific format, but.. rather not.

**Comment by rfuest** [comment] 2020-08-10 14:19
> In that case I think the color conversions are actually working fine, so long as the `C` for `Image` is correct?

They should. Do they work in your application?

> The docs aren't clear that the `C` for `Image` is for the image data, not the display.(And I now notice `draw_image` is generic)

The next version of e-g contains many changes in this part of the code and the updated docs should make it clearer where the color type needs to be specified.

`draw_image` was not generic over `C` in the 0.6 version of `DrawTarget` (it uses the same `C` as the `DrawTarget`), which made it unusable if the image color type and display color type didn't match. The 0.7 version of `DrawTarget` was rewritten and doesn't contain `draw_image` anymore.

> It's impossible to use images you don't statically know the format of in advance. You can't just load and display an image.

I will look into this when I do some other work on `tinytga` and `tinybmp`. But this will only be added for e-g 0.7, because the recent changes in e-g make future versions of these crates incompatible with e-g 0.6.

**Comment by rfuest** [comment] 2020-08-10 14:37
I've opened #424 to track the unknown color format issue.

**Comment by DianaNites** [comment] 2020-08-10 16:44
> They should. Do they work in your application?

Oh, huh, nevermind i guess they don't? I thought they did but it was late so mis-saw? `rust-pride.bmp`, which is a `Rgb565` bmp right? does not color correctly unless `Image<Bmp, Bgr565>`, matching the Display, is used?

**Comment by rfuest** [comment] 2020-08-10 17:09
Can you share your `DrawTarget` impl and the code you use to draw the image? It's hard to comment on this without seeing the code.

**Comment by DianaNites** [comment] 2020-08-11 21:09
[`DrawTarget`](https://github.com/DianaNites/uefi-graphics/blob/main/src/lib.rs)

[Drawing code](https://github.com/DianaNites/bootloader/blob/42ea09fbaf28d7995403ca5dcbbac37d59211d48/src/main.rs#L62)

<details>
<summary>Output from current code
</summary>

![Screenshot_20200811_170903](https://user-images.githubusercontent.com/5275194/89949112-5fdcd580-dbf5-11ea-88ac-54d4693b6e6f.png)

</details>

**Comment by rfuest** [comment] 2020-08-11 21:27
This conversion causes the dim display for the non generic `DrawTarget` impl:
https://github.com/DianaNites/bootloader/blob/42ea09fbaf28d7995403ca5dcbbac37d59211d48/src/main.rs#L135-L136
The values returned by `r()`, `g()` and `b()` are not scaled to 0-255 for color types with less than 8 bit per color channel. The commented out version should correctly scale the color channels.

**Comment by DianaNites** [comment] 2020-08-11 21:33
Oh yeah, that. I was trying to see if maybe it'd help get the colors correct, but the red and blue are still reversed.

**Comment by rfuest** [comment] 2020-08-11 21:39
Can you change the text to a color with `R != B` to make sure that works correctly?

**Comment by rfuest** [comment] 2020-08-11 21:50
Did you try to use an array for `write_value`, which is suggested in the docs for the `uefi` crate: https://docs.rs/uefi/0.5.0/uefi/proto/console/gop/struct.FrameBuffer.html#method.write_value?
Example: https://github.com/rust-osdev/uefi-rs/blob/ea0c557fc9d361a850b467575e3d512765a4939b/uefi-test-runner/src/proto/console/gop.rs#L60-L65

**Comment by DianaNites** [comment] 2020-08-11 22:47
[`DrawTarget`](https://github.com/DianaNites/uefi-graphics/blob/851c28775ff4f139fe2a9e2c7decac8f5ccb52b8/src/lib.rs#L35-L45)

[Drawing](https://github.com/DianaNites/bootloader/blob/4d1692dfbc7646670b1c3187e1cdae90212a74a2/src/main.rs#L69-L71)

Didn't even notice my text had R == B.

Did both of your suggestions and, uh,

<details>
<summary>Thats not right, both texts are red, but they should be blue?</summary>

![Screenshot_20200811_182358](https://user-images.githubusercontent.com/5275194/89954879-df6fa200-dbff-11ea-80a2-ea44122a65fb.png)


</details>

**Comment by rfuest** [comment] 2020-08-12 14:12
The UEFI GOP specs contain the following description:
![grafik](https://user-images.githubusercontent.com/226123/90024185-df7da980-dcb4-11ea-9fe7-8040ec3a92b5.png)

According to this description the bytes in RGB modes should be organized as R, G, B in memory regardless of the endianness of the machine. By using `into_ne_bytes` on an x86_64 machine you will get the reversed order.

**Comment by DianaNites** [comment] 2020-08-12 15:01
> By using into_ne_bytes on an x86_64 machine you will get the reversed order.

But [`to_ne_bytes`](https://doc.rust-lang.org/stable/src/core/num/mod.rs.html#4330-4339) does nothing except transmute to an array, through a union. It does not change the order of anything?

**Comment by DianaNites** [comment] 2020-08-12 15:06
> By using into_ne_bytes on an x86_64 machine you will get the reversed order.

But [`to_ne_bytes`](https://doc.rust-lang.org/stable/src/core/num/mod.rs.html#4330-4339) does nothing except directly transmute to an array.(through a union for const) It does not change the order of anything?

<details>
<summary>Changing it to `to_be_bytes`, which I guess would "un-reverse" it? is substantially worse. And `to_le_bytes` would of course be a noop on x86</summary>

![Screenshot_20200812_110422](https://user-images.githubusercontent.com/5275194/90031749-96652f80-dc8b-11ea-9cf4-c0709a7abdcb.png)

</details>

**Comment by rfuest** [comment] 2020-08-12 16:21
> But [`to_ne_bytes`](https://doc.rust-lang.org/stable/src/core/num/mod.rs.html#4330-4339) does nothing except directly transmute to an array.(through a union for const) It does not change the order of anything?

`Rgb888::new(0x11, 0x22, 0x33).into_storage()` results in an `u32` with a value of `0x00112233`. When you convert that value into an array by using `to_ne_bytes` on an `x86_64` machine you will get: `[0x33, 0x22, 0x11, 0x00]`.

> Changing it to `to_be_bytes`, which I guess would "un-reverse" it? is substantially worse. And `to_le_bytes` would of course be a noop on x86

The resulting array in this case would be `[0x00, 0x11, 0x22, 0x33]`, so you will need to remove the first element and not the last element of the array when copying it to the framebuffer.

**Comment by DianaNites** [comment] 2020-08-12 17:16
<details>
<summary>That seems to have done the trick? Thanks so much for your help.

Maybe the color types should provide a way to get an array in the appropriate format so they don't depend on endianness like this? Seems weird that `Rgb888` isn't actually laid out as `Rgb888` and all.

With the problem with this figured out and #424 for dynamic images, I guess this can be closed?
</summary>

![Screenshot_20200812_130533](https://user-images.githubusercontent.com/5275194/90045046-83a72680-dc9c-11ea-8f9c-795ea3d71be2.png)

</details>

**Comment by rfuest** [comment] 2020-08-12 19:16
> Maybe the color types should provide a way to get an array in the appropriate format so they don't depend on endianness like this?

That's a good idea. I've implemented this in PR #429.

> Seems weird that `Rgb888` isn't actually laid out as `Rgb888` and all.

That depends on the endianness of the machine and I agree that it can get weird.

> With the problem with this figured out and #424 for dynamic images, I guess this can be closed?

I'm glad that it works now and if you don't have any additional questions feel free to close the issue.

**Closed** 2020-08-12 19:38 UTC
